FROM node as build
WORKDIR /build
COPY ./frontend/ .
RUN npm install
RUN npm run build

FROM nginx
WORKDIR /usr/share/nginx/html
COPY --from=build /build/dist/ .

# COPY nginx config with custom proxy API path
COPY ./frontend/deploy/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
