apiVersion: v1
kind: Pod
metadata:
  name: frontend-backend
  labels:
    app: frontend-backend
spec:
  containers:
  - name: k8s-demo-frontend
    image: "k8sjenkinsturtorail/frontend"
    ports:
    - containerPort: 80
  - name: k8s-demo-backend
    image: "k8sjenkinsturtorail/backend"
    ports:
    - containerPort: 8888
