apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
  - name: k8s-demo-frontend
    image: "k8sjenkinsturtorail/frontend"
    ports: 
    - containerPort: 80